### ISSUE TITLE
i'm deploying your software but encoutering a few problems 

### ISSUE THREAD

**Issue by Thuan124** [yarox24/attack_monitor#5]
Adding autostart entry to Menu Start Startup folder
Traceback (most recent call last):
  File "installer.py", line 393, in <module>
    main()
  File "installer.py", line 379, in main
    action_install()
  File "installer.py", line 212, in action_install
    TEMPLATE_LINES = template.readlines()
  File "C:\Python37\Scripts\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "C:\Python37\Scripts\lib\encodings\utf_16.py", line 67, in _buffer_decode
    raise UnicodeError("UTF-16 stream does not start with BOM")
UnicodeError: UTF-16 stream does not start with BOM

**Comment by Thuan124** [comment]
thanks for your help.

**Comment by Thuan124** [comment]
please help me. @yarox24
